name: Test App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
        ports:
          - 3306:3306
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
          docker build -t clone-me .

      - name: Wait for containers to start
        run: sleep 10

      - name: Run API test
        run: |
          response_code=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080/clone-me)

          if [ "$response_code" -eq 200 ]; then
            echo "API test passed. Received a 200 response."
          else
            echo "API test failed. Received a non-200 response: $response_code"
            exit 1
          fi

