name: Test App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
          docker build -t clone-me .

      - name: Wait for containers to start
        run: sleep 10

      - name: Run tests
        run: |
          # Run your tests here

      - name: Stop and remove containers
        run: docker-compose down
